### ISSUE TITLE
can not resolve xx.d.ts paths?

### ISSUE THREAD

**Issue by Rainnut** [simonhaenisch/rollup-plugin-typescript-paths#11]
expect
```diff
// xx.d.ts
-import { MethodInfo } from 'src/types/aa';
+import { MethodInfo } from './aa';
```
├── types
│   ├── aa.d.ts
│   ├── xx.d.ts

**Comment by simonhaenisch** [comment]
Yeah, afaik there's no point in resolving to `.d.ts` files because they only contain types?

https://github.com/simonhaenisch/rollup-plugin-typescript-paths/blob/5aec0796e3ca62b8a630625e109730852d50ea6d/index.ts#L36-L38

What would you want to import from a declaration file that is relevant at runtime where it's just JS?

**Comment by simonhaenisch** [comment]
Maybe you missed the part in the readme where it says this plugin is only for use cases where you've already transpiled your TS to JS before running it through rollup?

**Comment by simonhaenisch** [comment]
Closing this for now but if you can present a valid use case for resolving to declaration files, I'll re-open.
